Module2 task1
htmlacademy-adaptive/2068313-cat-energy-26 pull request #2
Opened 2022-07-31 13:53 UTC by naumovn808

2022-07-31 20:27 UTC, Zakamsky requested changes
Объем очень большой, вижу что ты постарался, но что то БЭМ тебя покусал...
Знаю что ты без труда все поправишь.

Проверь пожалуйста шапку и подвал на всех страницах, я написал только на одной, но там общие ошибки.

2022-07-31 20:27 UTC, Zakamsky commented on source/index.html
> +          <li class="site-list__item site-list__item--active">
а где блок `site-list`? 
элементы не могут жить без блока.

2022-07-31 20:27 UTC, Zakamsky commented on source/index.html
> +      </div>
а список закрыть?
ты в валидаторе не проверил да?
ай яй яй...

2022-07-31 20:27 UTC, Zakamsky commented on source/index.html
> +        <img class="poster__img" src="img/poster.jpg" alt="банка с едой?." width="280" height="270">
Класс постер может быть вырезан блокировщиком рекламы. т.е. не класс а весь элемент с ним.
В будущем старайся избегать похожих на рекламу классов.
Хотя может быть я паранойю... в общем требований у нас таких конечно же нет.

2022-07-31 20:27 UTC, Zakamsky commented on source/index.html
> +        <h3 class="reduce__title">похудение</h3>
сегодня у нас есть класс `reduce` он я так понял про потерю веса, а завтра мы его используем для всех остальных программ...
для класса надо использовать что то нейтральное, независимое от содержимого
ну хотя бы `programm`

2022-07-31 20:27 UTC, Zakamsky commented on source/index.html
> +        <h3 class="reduce__title">Набор массы</h3>
а, ну вот =)
кстати тут у нас блок один, а элементы в нем от другого.
приемные наверное...

2022-07-31 20:27 UTC, Zakamsky commented on source/index.html
> +        </div>
неужели это прямо разные элементы все, с разными стилями, или там только урл картинки будет отличаться?
если второе так может это один элемент с модификаторами?

з.ы. и что тут у нас за диватоз?

2022-07-31 20:27 UTC, Zakamsky commented on source/index.html
> +        <h3 class="example__subtitle">Затраты на питание: 15 000 РУБ. </h3>
а что "оглавляет" этот заголовок?

2022-07-31 20:27 UTC, Zakamsky commented on source/index.html
> +            <p class="lider__desc">стало</p>
очипятка...

2022-07-31 20:27 UTC, Zakamsky commented on source/index.html
> +      <div class="location__icon"></div>
мы никак не свяжем эту иконку и фрэйм... т.ч. если очень хочется вставить иконку стоит глянуть на апи, или не делать иконку, это допустимо.

2022-07-31 20:27 UTC, Zakamsky commented on source/index.html
> +          <span class="visually-hidden">в контакте.</span>
а где блок `.social`?
может прямо:
```html
<ul class="social">
```

2022-07-31 20:27 UTC, Zakamsky commented on source/catalog.html
> +          </table>
тут можно конечно использовать таблицу, но с очень большой натяжкой...
хотя сперва давай про валидность - `th` у нас от какой колонки? кол-во колонок в штмл таблице должно совпадать, если не использованы специальные атрибуты. Валидатор в шоке немного...

Теперь о таблицах в целом - (мы обсуждали этот вопрос очень долго в чате): 
Таблица - это в первую очередь вертикальная связь данных. т.е. есть ряды и есть колонки и нам важно понимать что в разных рядах есть одинаковые данные в одной колонке и иметь возможность их сравнить.

тут такой связи нет, это три не связанных между собой строки...

В общем таблицу надо либо починить, либо убрать.

2022-07-31 20:27 UTC, Zakamsky commented on source/catalog.html
> +          <img class="card__img" src="img/energy-orange.jpg" alt="cat energy 1000g." width="68" height="86">
а еще диватоз опять... Может хоть артикл? (но помни что ему нужен заголовок.)

2022-07-31 20:27 UTC, Zakamsky commented on source/catalog.html
> +      </div>
А вот тут у нас явная вертикальная связь - в каждой строке есть:
- название
- объем
- цена
но тут мы не делаем таблицу почему то...
В общем если и делать где то таблицу - то тут самое место!

2022-07-31 20:27 UTC, Zakamsky commented on source/catalog.html
> +      </div>
ну или хотя бы див заменить на что то осмысленное...

2022-07-31 20:27 UTC, Zakamsky commented on source/catalog.html
> +        <p class="additioncard__desc">100 Р.</p>
слона то я чуть и не проморгал.
Элементы в блоке `addition-card` из какого то блока `additioncard`...
опять подкидыши?

2022-07-31 20:27 UTC, Zakamsky commented on source/catalog.html
> +          </table>
upd: а где блок `table`?

2022-07-31 20:27 UTC, Zakamsky commented on source/catalog.html
> +        <h3 class="additioncard-gift__title">Закажите все
опять элемент подкидышь...

2022-07-31 20:27 UTC, Zakamsky commented on source/form.html
> +    <p class="form__desc">Заполните анкету, и мы подберем
у нас тут, и еще ниже, есть элементы блока `form` но такого блока нигде нет...

2022-07-31 20:27 UTC, Zakamsky commented on source/form.html
> +          <p class="input-desc">ИМЯ:*</p>
Этот элемент нельзя вкладывать в лэйбл, `span`?

2022-07-31 20:27 UTC, Zakamsky commented on source/form.html
> +        <legend class="legend__title">
хм... а где блок `legend`?

2022-07-31 20:27 UTC, Zakamsky commented on source/form.html
> +        </label>
![image](https://user-images.githubusercontent.com/35491086/182043915-c5a10ac0-11c3-4ad4-949d-8b676ac7e439.png)

2022-07-31 20:27 UTC, Zakamsky commented on source/form.html
> +        </label>
вес и возраст точно текстовая информация?

2022-07-31 20:27 UTC, Zakamsky commented on source/form.html
> +      <a href="#" class="button form-button" type="submit">отправить заявку</a>
эээ а куда ведет эта ссылка, и как нам отправить форму?
кстати валидатор возмущен атрибутом `type="submit"` у ссылки...

2022-08-01 13:54 UTC, naumovn808 commented on source/index.html
> +      </div>
если честно, валидатором проверял, молчал он)

2022-08-01 13:59 UTC, naumovn808 commented on source/index.html
> +        </div>
я сделал дивами, потому что мне так показалось будет прооще, там иконки надо делать напротив текста

2022-08-01 22:03 UTC, merged